version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:bullseye"
    ports: 
      - 5432:5432
    env_file: .env_docker
    healthcheck:
      test: "/usr/bin/psql -U postgres postgres"
      interval: 2s
      timeout: 30s
      retries: 15
